# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transporte.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10transporte.proto\x1a\x1fgoogle/protobuf/timestamp.proto\".\n\tUbicacion\x12\x0f\n\x07latitud\x18\x01 \x01(\x01\x12\x10\n\x08longitud\x18\x02 \x01(\x01\"\xb5\x01\n\x0cStartRequest\x12\x0f\n\x07taxi_id\x18\x01 \x01(\t\x12\x14\n\x0c\x63onductor_id\x18\x02 \x01(\t\x12\x13\n\x0bpasajero_id\x18\x03 \x03(\t\x12\x1e\n\ntipo_viaje\x18\x04 \x01(\x0e\x32\n.TipoViaje\x12\x1d\n\tubicacion\x18\x05 \x01(\x0b\x32\n.Ubicacion\x12*\n\x06tiempo\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"8\n\rStartResponse\x12\x10\n\x08viaje_id\x18\x01 \x01(\t\x12\x15\n\rcosto_cliente\x18\x02 \x01(\x01*:\n\tTipoViaje\x12\t\n\x05UNSET\x10\x00\x12\x0b\n\x07REGULAR\x10\x01\x12\x08\n\x04POOL\x10\x02\x12\x0b\n\x07PREMIUM\x10\x03\x32\x33\n\tViaje_rpc\x12&\n\x05Start\x12\r.StartRequest\x1a\x0e.StartResponseb\x06proto3')

_TIPOVIAJE = DESCRIPTOR.enum_types_by_name['TipoViaje']
TipoViaje = enum_type_wrapper.EnumTypeWrapper(_TIPOVIAJE)
UNSET = 0
REGULAR = 1
POOL = 2
PREMIUM = 3


_UBICACION = DESCRIPTOR.message_types_by_name['Ubicacion']
_STARTREQUEST = DESCRIPTOR.message_types_by_name['StartRequest']
_STARTRESPONSE = DESCRIPTOR.message_types_by_name['StartResponse']
Ubicacion = _reflection.GeneratedProtocolMessageType('Ubicacion', (_message.Message,), {
  'DESCRIPTOR' : _UBICACION,
  '__module__' : 'transporte_pb2'
  # @@protoc_insertion_point(class_scope:Ubicacion)
  })
_sym_db.RegisterMessage(Ubicacion)

StartRequest = _reflection.GeneratedProtocolMessageType('StartRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTREQUEST,
  '__module__' : 'transporte_pb2'
  # @@protoc_insertion_point(class_scope:StartRequest)
  })
_sym_db.RegisterMessage(StartRequest)

StartResponse = _reflection.GeneratedProtocolMessageType('StartResponse', (_message.Message,), {
  'DESCRIPTOR' : _STARTRESPONSE,
  '__module__' : 'transporte_pb2'
  # @@protoc_insertion_point(class_scope:StartResponse)
  })
_sym_db.RegisterMessage(StartResponse)

_VIAJE_RPC = DESCRIPTOR.services_by_name['Viaje_rpc']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TIPOVIAJE._serialized_start=343
  _TIPOVIAJE._serialized_end=401
  _UBICACION._serialized_start=53
  _UBICACION._serialized_end=99
  _STARTREQUEST._serialized_start=102
  _STARTREQUEST._serialized_end=283
  _STARTRESPONSE._serialized_start=285
  _STARTRESPONSE._serialized_end=341
  _VIAJE_RPC._serialized_start=403
  _VIAJE_RPC._serialized_end=454
# @@protoc_insertion_point(module_scope)
